Update PT strings
hansemannn/studentenfutter-app pull request #23
Opened 2017-05-16 20:03 UTC by nuno

Update PT strings

2017-05-16 21:17 UTC, hansemannn commented
Can you clean-up the commits? We have 40 commits here.

2017-05-16 21:18 UTC, hansemannn commented
P.S.: Awesome that you keep track of the localizations, thanks Nuno!

2017-05-16 22:24 UTC, hansemannn requested changes
Please address the previous comments to continue.

2017-05-17 11:25 UTC, nuno commented
Not sure what happen

2017-05-17 13:46 UTC, hansemannn commented on patch.diff
> ++++ b/app/i18n/pt/strings.xml
Not sure what this is, but looks like something with your git client went really wrong. The relevant files have not been changed, but there is a `patch.diff` here. The other changes seem to come from an outdated master-fork. Can I commit them manually or do you want to do a new PR?

2017-05-17 13:48 UTC, nuno commented
let me try fix

2017-05-17 13:48 UTC, nuno commented on patch.diff
> ++++ b/app/i18n/pt/strings.xml
let me try fix

2017-05-17 13:53 UTC, closed without merging